# Version doesn't mean anything
version = 1 # required for logging config to work
# formatters format, use . to make a new one then name it
# in he handlers
[formatters.detailed]
class = "logging.Formatter"
#8s right-justifies level name, -8s will left-justify
format = "[%(asctime)s] [%(levelname)8s] - %(message)s"
datefmt = "%d/%m/%y %H:%M:%S"
# handlers are where logging info goes
[handlers.console]
class = "logging.StreamHandler"
formatter = "detailed"
[root]
level = "INFO"
handlers = ["console"]
