
version = 1 # required for logging config to work
[formatters.detailed]
class = "logging.Formatter"
format = "[%(asctime)s] [%(levelname)8s] - %(message)s"
datefmt = "%d/%m/%y %H:%M:%S"
[handlers.console]
class = "logging.StreamHandler"
formatter = "detailed"
[root]
level = "DEBUG"
handlers = ["console"]
