[seaborn]
palette = "deep"
context = "notebook"
style = "darkgrid"
font = 'sans-serif'
font_scale = 1
color_codes = true
#rc =  # overrides for above
# see https://seaborn.pydata.org/generated/seaborn.set_theme.html#seaborn.set_theme

[magnitude]
xlabel = "Julian Date"
ylabel = "Raw Magnitude"
color = "purple"

[differential_magnitude]
xlabel = "Julian Date"
ylabel = "Average Differential Magnitude"
color = "orange"

[error.bar]
fmt = "none"
color = "black"
capsize = 1
[error.fill]
alpha = 0.45 # How seethrough the fill lines are
label = "Error"
