# Where we put the output
# Each entry corresponds to a new folder
# Order matters
[base]
directory = "output"

[uniform]
uniform = "uniform"

[corrected]
corrected = "corrected"

[non_varying]
non_varying = "non_varying"

[varying]
varying = "varying"

[briefly_varying]
briefly_varying = "briefly_varying"

[excel]
excel = "excel"
