[seaborn]
# see https://seaborn.pydata.org/generated/seaborn.set_theme.html#seaborn.set_theme
palette = "deep"
context = "notebook"
style = "darkgrid"
font = 'sans-serif'
font_scale = 1
color_codes = true
#rc =  # overrides for above

[magnitude]
xlabel = "Time (UTC)"
ylabel = "Raw Magnitude"
color = "purple"

[differential_magnitude]
xlabel = "Time (UTC)"
ylabel = "Average Differential Magnitude"
color = "orange"

[time]
#based on https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior
fmt = "%H:%M:%S"
# tz = #must be https://docs.python.org/3/library/datetime.html#datetime.tzinfo
# usetex = false


[error.bar] #Error bars on both differential and normal magnitude
# see https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.errorbar.html?highlight=errorbar#matplotlib.axes.Axes.errorbar
fmt = "none"
color = "black"
capsize = 1

[error.fill]
# see https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.fill_between.html?highlight=fill_between#matplotlib.axes.Axes.fill_between
alpha = 0.45    # How seethrough the fill lines are
label = "Error"
